# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server import util


class CapacityValue(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, value: str=None, unit: str=None):  # noqa: E501
        """CapacityValue - a model defined in Swagger

        :param value: The value of this CapacityValue.  # noqa: E501
        :type value: str
        :param unit: The unit of this CapacityValue.  # noqa: E501
        :type unit: str
        """
        self.swagger_types = {
            'value': str,
            'unit': str
        }

        self.attribute_map = {
            'value': 'value',
            'unit': 'unit'
        }

        self._value = value
        self._unit = unit

    @classmethod
    def from_dict(cls, dikt) -> 'CapacityValue':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The capacity-value of this CapacityValue.  # noqa: E501
        :rtype: CapacityValue
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self) -> str:
        """Gets the value of this CapacityValue.


        :return: The value of this CapacityValue.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: str):
        """Sets the value of this CapacityValue.


        :param value: The value of this CapacityValue.
        :type value: str
        """

        self._value = value

    @property
    def unit(self) -> str:
        """Gets the unit of this CapacityValue.


        :return: The unit of this CapacityValue.
        :rtype: str
        """
        return self._unit

    @unit.setter
    def unit(self, unit: str):
        """Sets the unit of this CapacityValue.


        :param unit: The unit of this CapacityValue.
        :type unit: str
        """
        allowed_values = ["TB", "TBPS", "GB", "GBPS", "MB", "MBPS", "KB", "KBPS"]  # noqa: E501
        if unit not in allowed_values:
            raise ValueError(
                "Invalid value for `unit` ({0}), must be one of {1}"
                .format(unit, allowed_values)
            )

        self._unit = unit
