# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.connection import Connection  # noqa: F401,E501
from tapi_server import util


class GetConnectionDetailsRPCOutputSchema(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, connection: Connection=None):  # noqa: E501
        """GetConnectionDetailsRPCOutputSchema - a model defined in Swagger

        :param connection: The connection of this GetConnectionDetailsRPCOutputSchema.  # noqa: E501
        :type connection: Connection
        """
        self.swagger_types = {
            'connection': Connection
        }

        self.attribute_map = {
            'connection': 'connection'
        }

        self._connection = connection

    @classmethod
    def from_dict(cls, dikt) -> 'GetConnectionDetailsRPCOutputSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get-connection-detailsRPC_output_schema of this GetConnectionDetailsRPCOutputSchema.  # noqa: E501
        :rtype: GetConnectionDetailsRPCOutputSchema
        """
        return util.deserialize_model(dikt, cls)

    @property
    def connection(self) -> Connection:
        """Gets the connection of this GetConnectionDetailsRPCOutputSchema.


        :return: The connection of this GetConnectionDetailsRPCOutputSchema.
        :rtype: Connection
        """
        return self._connection

    @connection.setter
    def connection(self, connection: Connection):
        """Sets the connection of this GetConnectionDetailsRPCOutputSchema.


        :param connection: The connection of this GetConnectionDetailsRPCOutputSchema.
        :type connection: Connection
        """

        self._connection = connection
