# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server import util


class GetLinkDetailsRPCInputSchema(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, topology_id_or_name: str=None, link_id_or_name: str=None):  # noqa: E501
        """GetLinkDetailsRPCInputSchema - a model defined in Swagger

        :param topology_id_or_name: The topology_id_or_name of this GetLinkDetailsRPCInputSchema.  # noqa: E501
        :type topology_id_or_name: str
        :param link_id_or_name: The link_id_or_name of this GetLinkDetailsRPCInputSchema.  # noqa: E501
        :type link_id_or_name: str
        """
        self.swagger_types = {
            'topology_id_or_name': str,
            'link_id_or_name': str
        }

        self.attribute_map = {
            'topology_id_or_name': 'topology-id-or-name',
            'link_id_or_name': 'link-id-or-name'
        }

        self._topology_id_or_name = topology_id_or_name
        self._link_id_or_name = link_id_or_name

    @classmethod
    def from_dict(cls, dikt) -> 'GetLinkDetailsRPCInputSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get-link-detailsRPC_input_schema of this GetLinkDetailsRPCInputSchema.  # noqa: E501
        :rtype: GetLinkDetailsRPCInputSchema
        """
        return util.deserialize_model(dikt, cls)

    @property
    def topology_id_or_name(self) -> str:
        """Gets the topology_id_or_name of this GetLinkDetailsRPCInputSchema.


        :return: The topology_id_or_name of this GetLinkDetailsRPCInputSchema.
        :rtype: str
        """
        return self._topology_id_or_name

    @topology_id_or_name.setter
    def topology_id_or_name(self, topology_id_or_name: str):
        """Sets the topology_id_or_name of this GetLinkDetailsRPCInputSchema.


        :param topology_id_or_name: The topology_id_or_name of this GetLinkDetailsRPCInputSchema.
        :type topology_id_or_name: str
        """

        self._topology_id_or_name = topology_id_or_name

    @property
    def link_id_or_name(self) -> str:
        """Gets the link_id_or_name of this GetLinkDetailsRPCInputSchema.


        :return: The link_id_or_name of this GetLinkDetailsRPCInputSchema.
        :rtype: str
        """
        return self._link_id_or_name

    @link_id_or_name.setter
    def link_id_or_name(self, link_id_or_name: str):
        """Sets the link_id_or_name of this GetLinkDetailsRPCInputSchema.


        :param link_id_or_name: The link_id_or_name of this GetLinkDetailsRPCInputSchema.
        :type link_id_or_name: str
        """

        self._link_id_or_name = link_id_or_name
