# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.name_and_value import NameAndValue  # noqa: F401,E501
from tapi_server.models.service_spec import ServiceSpec  # noqa: F401,E501
from tapi_server import util


class NetworkTopologyService(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, uuid: str=None, name: List[NameAndValue]=None, topology: List[str]=None):  # noqa: E501
        """NetworkTopologyService - a model defined in Swagger

        :param uuid: The uuid of this NetworkTopologyService.  # noqa: E501
        :type uuid: str
        :param name: The name of this NetworkTopologyService.  # noqa: E501
        :type name: List[NameAndValue]
        :param topology: The topology of this NetworkTopologyService.  # noqa: E501
        :type topology: List[str]
        """
        self.swagger_types = {
            'uuid': str,
            'name': List[NameAndValue],
            'topology': List[str]
        }

        self.attribute_map = {
            'uuid': 'uuid',
            'name': 'name',
            'topology': 'topology'
        }

        self._uuid = uuid
        self._name = name
        self._topology = topology

    @classmethod
    def from_dict(cls, dikt) -> 'NetworkTopologyService':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The network-topology-service of this NetworkTopologyService.  # noqa: E501
        :rtype: NetworkTopologyService
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uuid(self) -> str:
        """Gets the uuid of this NetworkTopologyService.

        UUID: An identifier that is universally unique within an identifier space, where the identifier space is itself globally unique, and immutable. An UUID carries no semantics with respect to the purpose or state of the entity. UUID here uses string representation as defined in RFC 4122.  The canonical representation uses lowercase characters. Pattern: [0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-' + '[0-9a-fA-F]{4}-[0-9a-fA-F]{12}  Example of a UUID in string representation: f81d4fae-7dec-11d0-a765-00a0c91e6bf6  # noqa: E501

        :return: The uuid of this NetworkTopologyService.
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid: str):
        """Sets the uuid of this NetworkTopologyService.

        UUID: An identifier that is universally unique within an identifier space, where the identifier space is itself globally unique, and immutable. An UUID carries no semantics with respect to the purpose or state of the entity. UUID here uses string representation as defined in RFC 4122.  The canonical representation uses lowercase characters. Pattern: [0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-' + '[0-9a-fA-F]{4}-[0-9a-fA-F]{12}  Example of a UUID in string representation: f81d4fae-7dec-11d0-a765-00a0c91e6bf6  # noqa: E501

        :param uuid: The uuid of this NetworkTopologyService.
        :type uuid: str
        """

        self._uuid = uuid

    @property
    def name(self) -> List[NameAndValue]:
        """Gets the name of this NetworkTopologyService.

        List of names. A property of an entity with a value that is unique in some namespace but may change during the life of the entity. A name carries no semantics with respect to the purpose of the entity.  # noqa: E501

        :return: The name of this NetworkTopologyService.
        :rtype: List[NameAndValue]
        """
        return self._name

    @name.setter
    def name(self, name: List[NameAndValue]):
        """Sets the name of this NetworkTopologyService.

        List of names. A property of an entity with a value that is unique in some namespace but may change during the life of the entity. A name carries no semantics with respect to the purpose of the entity.  # noqa: E501

        :param name: The name of this NetworkTopologyService.
        :type name: List[NameAndValue]
        """

        self._name = name

    @property
    def topology(self) -> List[str]:
        """Gets the topology of this NetworkTopologyService.


        :return: The topology of this NetworkTopologyService.
        :rtype: List[str]
        """
        return self._topology

    @topology.setter
    def topology(self, topology: List[str]):
        """Sets the topology of this NetworkTopologyService.


        :param topology: The topology of this NetworkTopologyService.
        :type topology: List[str]
        """

        self._topology = topology
