# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.local_class import LocalClass  # noqa: F401,E501
from tapi_server.models.name_and_value import NameAndValue  # noqa: F401,E501
from tapi_server import util


class PathOptimizationConstraint(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, local_id: str=None, name: List[NameAndValue]=None, traffic_interruption: str=None):  # noqa: E501
        """PathOptimizationConstraint - a model defined in Swagger

        :param local_id: The local_id of this PathOptimizationConstraint.  # noqa: E501
        :type local_id: str
        :param name: The name of this PathOptimizationConstraint.  # noqa: E501
        :type name: List[NameAndValue]
        :param traffic_interruption: The traffic_interruption of this PathOptimizationConstraint.  # noqa: E501
        :type traffic_interruption: str
        """
        self.swagger_types = {
            'local_id': str,
            'name': List[NameAndValue],
            'traffic_interruption': str
        }

        self.attribute_map = {
            'local_id': 'local-id',
            'name': 'name',
            'traffic_interruption': 'traffic-interruption'
        }

        self._local_id = local_id
        self._name = name
        self._traffic_interruption = traffic_interruption

    @classmethod
    def from_dict(cls, dikt) -> 'PathOptimizationConstraint':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The path-optimization-constraint of this PathOptimizationConstraint.  # noqa: E501
        :rtype: PathOptimizationConstraint
        """
        return util.deserialize_model(dikt, cls)

    @property
    def local_id(self) -> str:
        """Gets the local_id of this PathOptimizationConstraint.


        :return: The local_id of this PathOptimizationConstraint.
        :rtype: str
        """
        return self._local_id

    @local_id.setter
    def local_id(self, local_id: str):
        """Sets the local_id of this PathOptimizationConstraint.


        :param local_id: The local_id of this PathOptimizationConstraint.
        :type local_id: str
        """

        self._local_id = local_id

    @property
    def name(self) -> List[NameAndValue]:
        """Gets the name of this PathOptimizationConstraint.

        List of names. A property of an entity with a value that is unique in some namespace but may change during the life of the entity. A name carries no semantics with respect to the purpose of the entity.  # noqa: E501

        :return: The name of this PathOptimizationConstraint.
        :rtype: List[NameAndValue]
        """
        return self._name

    @name.setter
    def name(self, name: List[NameAndValue]):
        """Sets the name of this PathOptimizationConstraint.

        List of names. A property of an entity with a value that is unique in some namespace but may change during the life of the entity. A name carries no semantics with respect to the purpose of the entity.  # noqa: E501

        :param name: The name of this PathOptimizationConstraint.
        :type name: List[NameAndValue]
        """

        self._name = name

    @property
    def traffic_interruption(self) -> str:
        """Gets the traffic_interruption of this PathOptimizationConstraint.


        :return: The traffic_interruption of this PathOptimizationConstraint.
        :rtype: str
        """
        return self._traffic_interruption

    @traffic_interruption.setter
    def traffic_interruption(self, traffic_interruption: str):
        """Sets the traffic_interruption of this PathOptimizationConstraint.


        :param traffic_interruption: The traffic_interruption of this PathOptimizationConstraint.
        :type traffic_interruption: str
        """

        self._traffic_interruption = traffic_interruption
