# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server import util


class TimeRange(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, end_time: str=None, start_time: str=None):  # noqa: E501
        """TimeRange - a model defined in Swagger

        :param end_time: The end_time of this TimeRange.  # noqa: E501
        :type end_time: str
        :param start_time: The start_time of this TimeRange.  # noqa: E501
        :type start_time: str
        """
        self.swagger_types = {
            'end_time': str,
            'start_time': str
        }

        self.attribute_map = {
            'end_time': 'end-time',
            'start_time': 'start-time'
        }

        self._end_time = end_time
        self._start_time = start_time

    @classmethod
    def from_dict(cls, dikt) -> 'TimeRange':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The time-range of this TimeRange.  # noqa: E501
        :rtype: TimeRange
        """
        return util.deserialize_model(dikt, cls)

    @property
    def end_time(self) -> str:
        """Gets the end_time of this TimeRange.


        :return: The end_time of this TimeRange.
        :rtype: str
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time: str):
        """Sets the end_time of this TimeRange.


        :param end_time: The end_time of this TimeRange.
        :type end_time: str
        """

        self._end_time = end_time

    @property
    def start_time(self) -> str:
        """Gets the start_time of this TimeRange.


        :return: The start_time of this TimeRange.
        :rtype: str
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time: str):
        """Sets the start_time of this TimeRange.


        :param start_time: The start_time of this TimeRange.
        :type start_time: str
        """

        self._start_time = start_time
