# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server import util


class TapiOduMappingType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    AMP = "AMP"
    BMP = "BMP"
    GFP_F = "GFP-F"
    GMP = "GMP"
    TTP_GFP_BMP = "TTP_GFP_BMP"
    NULL = "NULL"

    def __init__(self):  # noqa: E501
        """TapiOduMappingType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'TapiOduMappingType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.odu.MappingType of this TapiOduMappingType.  # noqa: E501
        :rtype: TapiOduMappingType
        """
        return util.deserialize_model(dikt, cls)
