# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_connectivity_getconnectivityservicelist_output import TapiConnectivityGetconnectivityservicelistOutput  # noqa: F401,E501
from tapi_server import util


class TapiConnectivityGetConnectivityServiceList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, output=None):  # noqa: E501
        """TapiConnectivityGetConnectivityServiceList - a model defined in OpenAPI

        :param output: The output of this TapiConnectivityGetConnectivityServiceList.  # noqa: E501
        :type output: TapiConnectivityGetconnectivityservicelistOutput
        """
        self.openapi_types = {
            'output': TapiConnectivityGetconnectivityservicelistOutput
        }

        self.attribute_map = {
            'output': 'output'
        }

        self._output = output

    @classmethod
    def from_dict(cls, dikt) -> 'TapiConnectivityGetConnectivityServiceList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.connectivity.GetConnectivityServiceList of this TapiConnectivityGetConnectivityServiceList.  # noqa: E501
        :rtype: TapiConnectivityGetConnectivityServiceList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def output(self):
        """Gets the output of this TapiConnectivityGetConnectivityServiceList.


        :return: The output of this TapiConnectivityGetConnectivityServiceList.
        :rtype: TapiConnectivityGetconnectivityservicelistOutput
        """
        return self._output

    @output.setter
    def output(self, output):
        """Sets the output of this TapiConnectivityGetConnectivityServiceList.


        :param output: The output of this TapiConnectivityGetConnectivityServiceList.
        :type output: TapiConnectivityGetconnectivityservicelistOutput
        """

        self._output = output
