# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_photonic_media_media_channel_properties_pac import TapiPhotonicMediaMediaChannelPropertiesPac  # noqa: F401,E501
from tapi_server import util


class TapiPhotonicMediaOtsConnectionEndPointSpec(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, ots_media_channel=None):  # noqa: E501
        """TapiPhotonicMediaOtsConnectionEndPointSpec - a model defined in OpenAPI

        :param ots_media_channel: The ots_media_channel of this TapiPhotonicMediaOtsConnectionEndPointSpec.  # noqa: E501
        :type ots_media_channel: TapiPhotonicMediaMediaChannelPropertiesPac
        """
        self.openapi_types = {
            'ots_media_channel': TapiPhotonicMediaMediaChannelPropertiesPac
        }

        self.attribute_map = {
            'ots_media_channel': 'ots-media-channel'
        }

        self._ots_media_channel = ots_media_channel

    @classmethod
    def from_dict(cls, dikt) -> 'TapiPhotonicMediaOtsConnectionEndPointSpec':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.photonic.media.OtsConnectionEndPointSpec of this TapiPhotonicMediaOtsConnectionEndPointSpec.  # noqa: E501
        :rtype: TapiPhotonicMediaOtsConnectionEndPointSpec
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ots_media_channel(self):
        """Gets the ots_media_channel of this TapiPhotonicMediaOtsConnectionEndPointSpec.


        :return: The ots_media_channel of this TapiPhotonicMediaOtsConnectionEndPointSpec.
        :rtype: TapiPhotonicMediaMediaChannelPropertiesPac
        """
        return self._ots_media_channel

    @ots_media_channel.setter
    def ots_media_channel(self, ots_media_channel):
        """Sets the ots_media_channel of this TapiPhotonicMediaOtsConnectionEndPointSpec.


        :param ots_media_channel: The ots_media_channel of this TapiPhotonicMediaOtsConnectionEndPointSpec.
        :type ots_media_channel: TapiPhotonicMediaMediaChannelPropertiesPac
        """

        self._ots_media_channel = ots_media_channel
