# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_common_administrative_state import TapiCommonAdministrativeState  # noqa: F401,E501
from tapi_server.models.tapi_common_capacity import TapiCommonCapacity  # noqa: F401,E501
from tapi_server.models.tapi_common_layer_protocol_name import TapiCommonLayerProtocolName  # noqa: F401,E501
from tapi_server.models.tapi_common_lifecycle_state import TapiCommonLifecycleState  # noqa: F401,E501
from tapi_server.models.tapi_common_name_and_value import TapiCommonNameAndValue  # noqa: F401,E501
from tapi_server.models.tapi_common_operational_state import TapiCommonOperationalState  # noqa: F401,E501
from tapi_server.models.tapi_common_port_direction import TapiCommonPortDirection  # noqa: F401,E501
from tapi_server.models.tapi_common_port_role import TapiCommonPortRole  # noqa: F401,E501
from tapi_server.models.tapi_common_service_interface_point_ref import TapiCommonServiceInterfacePointRef  # noqa: F401,E501
from tapi_server.models.tapi_common_termination_direction import TapiCommonTerminationDirection  # noqa: F401,E501
from tapi_server.models.tapi_common_termination_state import TapiCommonTerminationState  # noqa: F401,E501
from tapi_server.models.tapi_photonic_media_media_channel_node_edge_point_spec import TapiPhotonicMediaMediaChannelNodeEdgePointSpec  # noqa: F401,E501
from tapi_server.models.tapi_photonic_media_node_edge_point_augmentation1 import TapiPhotonicMediaNodeEdgePointAugmentation1  # noqa: F401,E501
from tapi_server.models.tapi_topology_node_edge_point import TapiTopologyNodeEdgePoint  # noqa: F401,E501
from tapi_server.models.tapi_topology_node_edge_point_ref import TapiTopologyNodeEdgePointRef  # noqa: F401,E501
from tapi_server import util


class TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, media_channel_node_edge_point_spec=None, operational_state=None, lifecycle_state=None, administrative_state=None, available_capacity=None, total_potential_capacity=None, name=None, uuid=None, termination_direction=None, termination_state=None, link_port_role=None, mapped_service_interface_point=None, aggregated_node_edge_point=None, layer_protocol_name=None, link_port_direction=None, supported_cep_layer_protocol_qualifier=None):  # noqa: E501
        """TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint - a model defined in OpenAPI

        :param media_channel_node_edge_point_spec: The media_channel_node_edge_point_spec of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.  # noqa: E501
        :type media_channel_node_edge_point_spec: TapiPhotonicMediaMediaChannelNodeEdgePointSpec
        :param operational_state: The operational_state of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.  # noqa: E501
        :type operational_state: TapiCommonOperationalState
        :param lifecycle_state: The lifecycle_state of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.  # noqa: E501
        :type lifecycle_state: TapiCommonLifecycleState
        :param administrative_state: The administrative_state of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.  # noqa: E501
        :type administrative_state: TapiCommonAdministrativeState
        :param available_capacity: The available_capacity of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.  # noqa: E501
        :type available_capacity: TapiCommonCapacity
        :param total_potential_capacity: The total_potential_capacity of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.  # noqa: E501
        :type total_potential_capacity: TapiCommonCapacity
        :param name: The name of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.  # noqa: E501
        :type name: List[TapiCommonNameAndValue]
        :param uuid: The uuid of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.  # noqa: E501
        :type uuid: str
        :param termination_direction: The termination_direction of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.  # noqa: E501
        :type termination_direction: TapiCommonTerminationDirection
        :param termination_state: The termination_state of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.  # noqa: E501
        :type termination_state: TapiCommonTerminationState
        :param link_port_role: The link_port_role of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.  # noqa: E501
        :type link_port_role: TapiCommonPortRole
        :param mapped_service_interface_point: The mapped_service_interface_point of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.  # noqa: E501
        :type mapped_service_interface_point: List[TapiCommonServiceInterfacePointRef]
        :param aggregated_node_edge_point: The aggregated_node_edge_point of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.  # noqa: E501
        :type aggregated_node_edge_point: List[TapiTopologyNodeEdgePointRef]
        :param layer_protocol_name: The layer_protocol_name of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.  # noqa: E501
        :type layer_protocol_name: TapiCommonLayerProtocolName
        :param link_port_direction: The link_port_direction of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.  # noqa: E501
        :type link_port_direction: TapiCommonPortDirection
        :param supported_cep_layer_protocol_qualifier: The supported_cep_layer_protocol_qualifier of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.  # noqa: E501
        :type supported_cep_layer_protocol_qualifier: List[str]
        """
        self.openapi_types = {
            'media_channel_node_edge_point_spec': TapiPhotonicMediaMediaChannelNodeEdgePointSpec,
            'operational_state': TapiCommonOperationalState,
            'lifecycle_state': TapiCommonLifecycleState,
            'administrative_state': TapiCommonAdministrativeState,
            'available_capacity': TapiCommonCapacity,
            'total_potential_capacity': TapiCommonCapacity,
            'name': List[TapiCommonNameAndValue],
            'uuid': str,
            'termination_direction': TapiCommonTerminationDirection,
            'termination_state': TapiCommonTerminationState,
            'link_port_role': TapiCommonPortRole,
            'mapped_service_interface_point': List[TapiCommonServiceInterfacePointRef],
            'aggregated_node_edge_point': List[TapiTopologyNodeEdgePointRef],
            'layer_protocol_name': TapiCommonLayerProtocolName,
            'link_port_direction': TapiCommonPortDirection,
            'supported_cep_layer_protocol_qualifier': List[str]
        }

        self.attribute_map = {
            'media_channel_node_edge_point_spec': 'media-channel-node-edge-point-spec',
            'operational_state': 'operational-state',
            'lifecycle_state': 'lifecycle-state',
            'administrative_state': 'administrative-state',
            'available_capacity': 'available-capacity',
            'total_potential_capacity': 'total-potential-capacity',
            'name': 'name',
            'uuid': 'uuid',
            'termination_direction': 'termination-direction',
            'termination_state': 'termination-state',
            'link_port_role': 'link-port-role',
            'mapped_service_interface_point': 'mapped-service-interface-point',
            'aggregated_node_edge_point': 'aggregated-node-edge-point',
            'layer_protocol_name': 'layer-protocol-name',
            'link_port_direction': 'link-port-direction',
            'supported_cep_layer_protocol_qualifier': 'supported-cep-layer-protocol-qualifier'
        }

        self._media_channel_node_edge_point_spec = media_channel_node_edge_point_spec
        self._operational_state = operational_state
        self._lifecycle_state = lifecycle_state
        self._administrative_state = administrative_state
        self._available_capacity = available_capacity
        self._total_potential_capacity = total_potential_capacity
        self._name = name
        self._uuid = uuid
        self._termination_direction = termination_direction
        self._termination_state = termination_state
        self._link_port_role = link_port_role
        self._mapped_service_interface_point = mapped_service_interface_point
        self._aggregated_node_edge_point = aggregated_node_edge_point
        self._layer_protocol_name = layer_protocol_name
        self._link_port_direction = link_port_direction
        self._supported_cep_layer_protocol_qualifier = supported_cep_layer_protocol_qualifier

    @classmethod
    def from_dict(cls, dikt) -> 'TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.topology.getnodeedgepointdetails.output.NodeEdgePoint of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.  # noqa: E501
        :rtype: TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint
        """
        return util.deserialize_model(dikt, cls)

    @property
    def media_channel_node_edge_point_spec(self):
        """Gets the media_channel_node_edge_point_spec of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.


        :return: The media_channel_node_edge_point_spec of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.
        :rtype: TapiPhotonicMediaMediaChannelNodeEdgePointSpec
        """
        return self._media_channel_node_edge_point_spec

    @media_channel_node_edge_point_spec.setter
    def media_channel_node_edge_point_spec(self, media_channel_node_edge_point_spec):
        """Sets the media_channel_node_edge_point_spec of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.


        :param media_channel_node_edge_point_spec: The media_channel_node_edge_point_spec of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.
        :type media_channel_node_edge_point_spec: TapiPhotonicMediaMediaChannelNodeEdgePointSpec
        """

        self._media_channel_node_edge_point_spec = media_channel_node_edge_point_spec

    @property
    def operational_state(self):
        """Gets the operational_state of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.


        :return: The operational_state of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.
        :rtype: TapiCommonOperationalState
        """
        return self._operational_state

    @operational_state.setter
    def operational_state(self, operational_state):
        """Sets the operational_state of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.


        :param operational_state: The operational_state of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.
        :type operational_state: TapiCommonOperationalState
        """

        self._operational_state = operational_state

    @property
    def lifecycle_state(self):
        """Gets the lifecycle_state of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.


        :return: The lifecycle_state of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.
        :rtype: TapiCommonLifecycleState
        """
        return self._lifecycle_state

    @lifecycle_state.setter
    def lifecycle_state(self, lifecycle_state):
        """Sets the lifecycle_state of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.


        :param lifecycle_state: The lifecycle_state of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.
        :type lifecycle_state: TapiCommonLifecycleState
        """

        self._lifecycle_state = lifecycle_state

    @property
    def administrative_state(self):
        """Gets the administrative_state of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.


        :return: The administrative_state of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.
        :rtype: TapiCommonAdministrativeState
        """
        return self._administrative_state

    @administrative_state.setter
    def administrative_state(self, administrative_state):
        """Sets the administrative_state of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.


        :param administrative_state: The administrative_state of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.
        :type administrative_state: TapiCommonAdministrativeState
        """

        self._administrative_state = administrative_state

    @property
    def available_capacity(self):
        """Gets the available_capacity of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.


        :return: The available_capacity of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.
        :rtype: TapiCommonCapacity
        """
        return self._available_capacity

    @available_capacity.setter
    def available_capacity(self, available_capacity):
        """Sets the available_capacity of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.


        :param available_capacity: The available_capacity of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.
        :type available_capacity: TapiCommonCapacity
        """

        self._available_capacity = available_capacity

    @property
    def total_potential_capacity(self):
        """Gets the total_potential_capacity of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.


        :return: The total_potential_capacity of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.
        :rtype: TapiCommonCapacity
        """
        return self._total_potential_capacity

    @total_potential_capacity.setter
    def total_potential_capacity(self, total_potential_capacity):
        """Sets the total_potential_capacity of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.


        :param total_potential_capacity: The total_potential_capacity of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.
        :type total_potential_capacity: TapiCommonCapacity
        """

        self._total_potential_capacity = total_potential_capacity

    @property
    def name(self):
        """Gets the name of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.

        List of names. A property of an entity with a value that is unique in some namespace but may change during the life of the entity. A name carries no semantics with respect to the purpose of the entity.  # noqa: E501

        :return: The name of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.
        :rtype: List[TapiCommonNameAndValue]
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.

        List of names. A property of an entity with a value that is unique in some namespace but may change during the life of the entity. A name carries no semantics with respect to the purpose of the entity.  # noqa: E501

        :param name: The name of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.
        :type name: List[TapiCommonNameAndValue]
        """

        self._name = name

    @property
    def uuid(self):
        """Gets the uuid of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.

        UUID: An identifier that is universally unique within an identifier space, where the identifier space is itself globally unique, and immutable. An UUID carries no semantics with respect to the purpose or state of the entity.                      UUID here uses string representation as defined in RFC 4122.  The canonical representation uses lowercase characters.                      Pattern: [0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-' + '[0-9a-fA-F]{4}-[0-9a-fA-F]{12}                       Example of a UUID in string representation: f81d4fae-7dec-11d0-a765-00a0c91e6bf6  # noqa: E501

        :return: The uuid of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.

        UUID: An identifier that is universally unique within an identifier space, where the identifier space is itself globally unique, and immutable. An UUID carries no semantics with respect to the purpose or state of the entity.                      UUID here uses string representation as defined in RFC 4122.  The canonical representation uses lowercase characters.                      Pattern: [0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-' + '[0-9a-fA-F]{4}-[0-9a-fA-F]{12}                       Example of a UUID in string representation: f81d4fae-7dec-11d0-a765-00a0c91e6bf6  # noqa: E501

        :param uuid: The uuid of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.
        :type uuid: str
        """

        self._uuid = uuid

    @property
    def termination_direction(self):
        """Gets the termination_direction of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.


        :return: The termination_direction of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.
        :rtype: TapiCommonTerminationDirection
        """
        return self._termination_direction

    @termination_direction.setter
    def termination_direction(self, termination_direction):
        """Sets the termination_direction of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.


        :param termination_direction: The termination_direction of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.
        :type termination_direction: TapiCommonTerminationDirection
        """

        self._termination_direction = termination_direction

    @property
    def termination_state(self):
        """Gets the termination_state of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.


        :return: The termination_state of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.
        :rtype: TapiCommonTerminationState
        """
        return self._termination_state

    @termination_state.setter
    def termination_state(self, termination_state):
        """Sets the termination_state of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.


        :param termination_state: The termination_state of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.
        :type termination_state: TapiCommonTerminationState
        """

        self._termination_state = termination_state

    @property
    def link_port_role(self):
        """Gets the link_port_role of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.


        :return: The link_port_role of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.
        :rtype: TapiCommonPortRole
        """
        return self._link_port_role

    @link_port_role.setter
    def link_port_role(self, link_port_role):
        """Sets the link_port_role of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.


        :param link_port_role: The link_port_role of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.
        :type link_port_role: TapiCommonPortRole
        """

        self._link_port_role = link_port_role

    @property
    def mapped_service_interface_point(self):
        """Gets the mapped_service_interface_point of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.

        NodeEdgePoint mapped to more than ServiceInterfacePoint (slicing/virtualizing) or a ServiceInterfacePoint mapped to more than one NodeEdgePoint (load balancing/Resilience) should be considered experimental  # noqa: E501

        :return: The mapped_service_interface_point of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.
        :rtype: List[TapiCommonServiceInterfacePointRef]
        """
        return self._mapped_service_interface_point

    @mapped_service_interface_point.setter
    def mapped_service_interface_point(self, mapped_service_interface_point):
        """Sets the mapped_service_interface_point of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.

        NodeEdgePoint mapped to more than ServiceInterfacePoint (slicing/virtualizing) or a ServiceInterfacePoint mapped to more than one NodeEdgePoint (load balancing/Resilience) should be considered experimental  # noqa: E501

        :param mapped_service_interface_point: The mapped_service_interface_point of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.
        :type mapped_service_interface_point: List[TapiCommonServiceInterfacePointRef]
        """

        self._mapped_service_interface_point = mapped_service_interface_point

    @property
    def aggregated_node_edge_point(self):
        """Gets the aggregated_node_edge_point of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.

        none  # noqa: E501

        :return: The aggregated_node_edge_point of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.
        :rtype: List[TapiTopologyNodeEdgePointRef]
        """
        return self._aggregated_node_edge_point

    @aggregated_node_edge_point.setter
    def aggregated_node_edge_point(self, aggregated_node_edge_point):
        """Sets the aggregated_node_edge_point of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.

        none  # noqa: E501

        :param aggregated_node_edge_point: The aggregated_node_edge_point of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.
        :type aggregated_node_edge_point: List[TapiTopologyNodeEdgePointRef]
        """

        self._aggregated_node_edge_point = aggregated_node_edge_point

    @property
    def layer_protocol_name(self):
        """Gets the layer_protocol_name of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.


        :return: The layer_protocol_name of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.
        :rtype: TapiCommonLayerProtocolName
        """
        return self._layer_protocol_name

    @layer_protocol_name.setter
    def layer_protocol_name(self, layer_protocol_name):
        """Sets the layer_protocol_name of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.


        :param layer_protocol_name: The layer_protocol_name of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.
        :type layer_protocol_name: TapiCommonLayerProtocolName
        """

        self._layer_protocol_name = layer_protocol_name

    @property
    def link_port_direction(self):
        """Gets the link_port_direction of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.


        :return: The link_port_direction of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.
        :rtype: TapiCommonPortDirection
        """
        return self._link_port_direction

    @link_port_direction.setter
    def link_port_direction(self, link_port_direction):
        """Sets the link_port_direction of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.


        :param link_port_direction: The link_port_direction of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.
        :type link_port_direction: TapiCommonPortDirection
        """

        self._link_port_direction = link_port_direction

    @property
    def supported_cep_layer_protocol_qualifier(self):
        """Gets the supported_cep_layer_protocol_qualifier of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.

        none  # noqa: E501

        :return: The supported_cep_layer_protocol_qualifier of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.
        :rtype: List[str]
        """
        return self._supported_cep_layer_protocol_qualifier

    @supported_cep_layer_protocol_qualifier.setter
    def supported_cep_layer_protocol_qualifier(self, supported_cep_layer_protocol_qualifier):
        """Sets the supported_cep_layer_protocol_qualifier of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.

        none  # noqa: E501

        :param supported_cep_layer_protocol_qualifier: The supported_cep_layer_protocol_qualifier of this TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint.
        :type supported_cep_layer_protocol_qualifier: List[str]
        """

        self._supported_cep_layer_protocol_qualifier = supported_cep_layer_protocol_qualifier
