# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_notification_getnotificationlist_output import TapiNotificationGetnotificationlistOutput  # noqa: F401,E501
from tapi_server import util


class TapiNotificationGetNotificationList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, output=None):  # noqa: E501
        """TapiNotificationGetNotificationList - a model defined in OpenAPI

        :param output: The output of this TapiNotificationGetNotificationList.  # noqa: E501
        :type output: TapiNotificationGetnotificationlistOutput
        """
        self.openapi_types = {
            'output': TapiNotificationGetnotificationlistOutput
        }

        self.attribute_map = {
            'output': 'output'
        }

        self._output = output

    @classmethod
    def from_dict(cls, dikt) -> 'TapiNotificationGetNotificationList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.notification.GetNotificationList of this TapiNotificationGetNotificationList.  # noqa: E501
        :rtype: TapiNotificationGetNotificationList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def output(self):
        """Gets the output of this TapiNotificationGetNotificationList.


        :return: The output of this TapiNotificationGetNotificationList.
        :rtype: TapiNotificationGetnotificationlistOutput
        """
        return self._output

    @output.setter
    def output(self, output):
        """Sets the output of this TapiNotificationGetNotificationList.


        :param output: The output of this TapiNotificationGetNotificationList.
        :type output: TapiNotificationGetnotificationlistOutput
        """

        self._output = output
