# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_oam_oam_job import TapiOamOamJob  # noqa: F401,E501
from tapi_server import util


class TapiOamGetoamjobOutput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, oam_job=None):  # noqa: E501
        """TapiOamGetoamjobOutput - a model defined in OpenAPI

        :param oam_job: The oam_job of this TapiOamGetoamjobOutput.  # noqa: E501
        :type oam_job: TapiOamOamJob
        """
        self.openapi_types = {
            'oam_job': TapiOamOamJob
        }

        self.attribute_map = {
            'oam_job': 'oam-job'
        }

        self._oam_job = oam_job

    @classmethod
    def from_dict(cls, dikt) -> 'TapiOamGetoamjobOutput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.oam.getoamjob.Output of this TapiOamGetoamjobOutput.  # noqa: E501
        :rtype: TapiOamGetoamjobOutput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def oam_job(self):
        """Gets the oam_job of this TapiOamGetoamjobOutput.


        :return: The oam_job of this TapiOamGetoamjobOutput.
        :rtype: TapiOamOamJob
        """
        return self._oam_job

    @oam_job.setter
    def oam_job(self, oam_job):
        """Sets the oam_job of this TapiOamGetoamjobOutput.


        :param oam_job: The oam_job of this TapiOamGetoamjobOutput.
        :type oam_job: TapiOamOamJob
        """

        self._oam_job = oam_job
