# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_oam_getoamservicelist_output import TapiOamGetoamservicelistOutput  # noqa: F401,E501
from tapi_server import util


class TapiOamGetOamServiceList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, output=None):  # noqa: E501
        """TapiOamGetOamServiceList - a model defined in OpenAPI

        :param output: The output of this TapiOamGetOamServiceList.  # noqa: E501
        :type output: TapiOamGetoamservicelistOutput
        """
        self.openapi_types = {
            'output': TapiOamGetoamservicelistOutput
        }

        self.attribute_map = {
            'output': 'output'
        }

        self._output = output

    @classmethod
    def from_dict(cls, dikt) -> 'TapiOamGetOamServiceList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.oam.GetOamServiceList of this TapiOamGetOamServiceList.  # noqa: E501
        :rtype: TapiOamGetOamServiceList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def output(self):
        """Gets the output of this TapiOamGetOamServiceList.


        :return: The output of this TapiOamGetOamServiceList.
        :rtype: TapiOamGetoamservicelistOutput
        """
        return self._output

    @output.setter
    def output(self, output):
        """Sets the output of this TapiOamGetOamServiceList.


        :param output: The output of this TapiOamGetOamServiceList.
        :type output: TapiOamGetoamservicelistOutput
        """

        self._output = output
