# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_notification_notification import TapiNotificationNotification  # noqa: F401,E501
from tapi_server.models.tapi_notification_notification_subscription_service import TapiNotificationNotificationSubscriptionService  # noqa: F401,E501
from tapi_server import util


class TapiNotificationNotificationContext(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, notif_subscription=None, notification=None):  # noqa: E501
        """TapiNotificationNotificationContext - a model defined in OpenAPI

        :param notif_subscription: The notif_subscription of this TapiNotificationNotificationContext.  # noqa: E501
        :type notif_subscription: List[TapiNotificationNotificationSubscriptionService]
        :param notification: The notification of this TapiNotificationNotificationContext.  # noqa: E501
        :type notification: List[TapiNotificationNotification]
        """
        self.openapi_types = {
            'notif_subscription': List[TapiNotificationNotificationSubscriptionService],
            'notification': List[TapiNotificationNotification]
        }

        self.attribute_map = {
            'notif_subscription': 'notif-subscription',
            'notification': 'notification'
        }

        self._notif_subscription = notif_subscription
        self._notification = notification

    @classmethod
    def from_dict(cls, dikt) -> 'TapiNotificationNotificationContext':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.notification.NotificationContext of this TapiNotificationNotificationContext.  # noqa: E501
        :rtype: TapiNotificationNotificationContext
        """
        return util.deserialize_model(dikt, cls)

    @property
    def notif_subscription(self):
        """Gets the notif_subscription of this TapiNotificationNotificationContext.

        none  # noqa: E501

        :return: The notif_subscription of this TapiNotificationNotificationContext.
        :rtype: List[TapiNotificationNotificationSubscriptionService]
        """
        return self._notif_subscription

    @notif_subscription.setter
    def notif_subscription(self, notif_subscription):
        """Sets the notif_subscription of this TapiNotificationNotificationContext.

        none  # noqa: E501

        :param notif_subscription: The notif_subscription of this TapiNotificationNotificationContext.
        :type notif_subscription: List[TapiNotificationNotificationSubscriptionService]
        """

        self._notif_subscription = notif_subscription

    @property
    def notification(self):
        """Gets the notification of this TapiNotificationNotificationContext.

        none  # noqa: E501

        :return: The notification of this TapiNotificationNotificationContext.
        :rtype: List[TapiNotificationNotification]
        """
        return self._notification

    @notification.setter
    def notification(self, notification):
        """Sets the notification of this TapiNotificationNotificationContext.

        none  # noqa: E501

        :param notification: The notification of this TapiNotificationNotificationContext.
        :type notification: List[TapiNotificationNotification]
        """

        self._notification = notification
