# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_common_getserviceinterfacepointlist_output import TapiCommonGetserviceinterfacepointlistOutput  # noqa: F401,E501
from tapi_server import util


class TapiCommonGetServiceInterfacePointList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, output=None):  # noqa: E501
        """TapiCommonGetServiceInterfacePointList - a model defined in OpenAPI

        :param output: The output of this TapiCommonGetServiceInterfacePointList.  # noqa: E501
        :type output: TapiCommonGetserviceinterfacepointlistOutput
        """
        self.openapi_types = {
            'output': TapiCommonGetserviceinterfacepointlistOutput
        }

        self.attribute_map = {
            'output': 'output'
        }

        self._output = output

    @classmethod
    def from_dict(cls, dikt) -> 'TapiCommonGetServiceInterfacePointList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.common.GetServiceInterfacePointList of this TapiCommonGetServiceInterfacePointList.  # noqa: E501
        :rtype: TapiCommonGetServiceInterfacePointList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def output(self):
        """Gets the output of this TapiCommonGetServiceInterfacePointList.


        :return: The output of this TapiCommonGetServiceInterfacePointList.
        :rtype: TapiCommonGetserviceinterfacepointlistOutput
        """
        return self._output

    @output.setter
    def output(self, output):
        """Sets the output of this TapiCommonGetServiceInterfacePointList.


        :param output: The output of this TapiCommonGetServiceInterfacePointList.
        :type output: TapiCommonGetserviceinterfacepointlistOutput
        """

        self._output = output
