# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_topology_topology_ref import TapiTopologyTopologyRef  # noqa: F401,E501
from tapi_server import util


class TapiTopologyLinkRef(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, topology_uuid=None, link_uuid=None):  # noqa: E501
        """TapiTopologyLinkRef - a model defined in OpenAPI

        :param topology_uuid: The topology_uuid of this TapiTopologyLinkRef.  # noqa: E501
        :type topology_uuid: str
        :param link_uuid: The link_uuid of this TapiTopologyLinkRef.  # noqa: E501
        :type link_uuid: str
        """
        self.openapi_types = {
            'topology_uuid': str,
            'link_uuid': str
        }

        self.attribute_map = {
            'topology_uuid': 'topology-uuid',
            'link_uuid': 'link-uuid'
        }

        self._topology_uuid = topology_uuid
        self._link_uuid = link_uuid

    @classmethod
    def from_dict(cls, dikt) -> 'TapiTopologyLinkRef':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.topology.LinkRef of this TapiTopologyLinkRef.  # noqa: E501
        :rtype: TapiTopologyLinkRef
        """
        return util.deserialize_model(dikt, cls)

    @property
    def topology_uuid(self):
        """Gets the topology_uuid of this TapiTopologyLinkRef.

        none  # noqa: E501

        :return: The topology_uuid of this TapiTopologyLinkRef.
        :rtype: str
        """
        return self._topology_uuid

    @topology_uuid.setter
    def topology_uuid(self, topology_uuid):
        """Sets the topology_uuid of this TapiTopologyLinkRef.

        none  # noqa: E501

        :param topology_uuid: The topology_uuid of this TapiTopologyLinkRef.
        :type topology_uuid: str
        """

        self._topology_uuid = topology_uuid

    @property
    def link_uuid(self):
        """Gets the link_uuid of this TapiTopologyLinkRef.

        none  # noqa: E501

        :return: The link_uuid of this TapiTopologyLinkRef.
        :rtype: str
        """
        return self._link_uuid

    @link_uuid.setter
    def link_uuid(self, link_uuid):
        """Sets the link_uuid of this TapiTopologyLinkRef.

        none  # noqa: E501

        :param link_uuid: The link_uuid of this TapiTopologyLinkRef.
        :type link_uuid: str
        """

        self._link_uuid = link_uuid
