# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_common_admin_state_pac import TapiCommonAdminStatePac  # noqa: F401,E501
from tapi_server.models.tapi_common_administrative_state import TapiCommonAdministrativeState  # noqa: F401,E501
from tapi_server.models.tapi_common_global_class import TapiCommonGlobalClass  # noqa: F401,E501
from tapi_server.models.tapi_common_lifecycle_state import TapiCommonLifecycleState  # noqa: F401,E501
from tapi_server.models.tapi_common_name_and_value import TapiCommonNameAndValue  # noqa: F401,E501
from tapi_server.models.tapi_common_operational_state import TapiCommonOperationalState  # noqa: F401,E501
from tapi_server.models.tapi_common_time_range import TapiCommonTimeRange  # noqa: F401,E501
from tapi_server.models.tapi_oam_oam_profile_ref import TapiOamOamProfileRef  # noqa: F401,E501
from tapi_server.models.tapi_oam_oam_service_end_point_ref import TapiOamOamServiceEndPointRef  # noqa: F401,E501
from tapi_server.models.tapi_oam_pm_current_data import TapiOamPmCurrentData  # noqa: F401,E501
from tapi_server import util


class TapiOamOamJob(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, operational_state=None, lifecycle_state=None, administrative_state=None, name=None, uuid=None, schedule=None, oam_profile=None, pm_current_data=None, creation_time=None, oam_service_end_point=None, oam_job_type=None):  # noqa: E501
        """TapiOamOamJob - a model defined in OpenAPI

        :param operational_state: The operational_state of this TapiOamOamJob.  # noqa: E501
        :type operational_state: TapiCommonOperationalState
        :param lifecycle_state: The lifecycle_state of this TapiOamOamJob.  # noqa: E501
        :type lifecycle_state: TapiCommonLifecycleState
        :param administrative_state: The administrative_state of this TapiOamOamJob.  # noqa: E501
        :type administrative_state: TapiCommonAdministrativeState
        :param name: The name of this TapiOamOamJob.  # noqa: E501
        :type name: List[TapiCommonNameAndValue]
        :param uuid: The uuid of this TapiOamOamJob.  # noqa: E501
        :type uuid: str
        :param schedule: The schedule of this TapiOamOamJob.  # noqa: E501
        :type schedule: TapiCommonTimeRange
        :param oam_profile: The oam_profile of this TapiOamOamJob.  # noqa: E501
        :type oam_profile: TapiOamOamProfileRef
        :param pm_current_data: The pm_current_data of this TapiOamOamJob.  # noqa: E501
        :type pm_current_data: List[TapiOamPmCurrentData]
        :param creation_time: The creation_time of this TapiOamOamJob.  # noqa: E501
        :type creation_time: str
        :param oam_service_end_point: The oam_service_end_point of this TapiOamOamJob.  # noqa: E501
        :type oam_service_end_point: List[TapiOamOamServiceEndPointRef]
        :param oam_job_type: The oam_job_type of this TapiOamOamJob.  # noqa: E501
        :type oam_job_type: str
        """
        self.openapi_types = {
            'operational_state': TapiCommonOperationalState,
            'lifecycle_state': TapiCommonLifecycleState,
            'administrative_state': TapiCommonAdministrativeState,
            'name': List[TapiCommonNameAndValue],
            'uuid': str,
            'schedule': TapiCommonTimeRange,
            'oam_profile': TapiOamOamProfileRef,
            'pm_current_data': List[TapiOamPmCurrentData],
            'creation_time': str,
            'oam_service_end_point': List[TapiOamOamServiceEndPointRef],
            'oam_job_type': str
        }

        self.attribute_map = {
            'operational_state': 'operational-state',
            'lifecycle_state': 'lifecycle-state',
            'administrative_state': 'administrative-state',
            'name': 'name',
            'uuid': 'uuid',
            'schedule': 'schedule',
            'oam_profile': 'oam-profile',
            'pm_current_data': 'pm-current-data',
            'creation_time': 'creation-time',
            'oam_service_end_point': 'oam-service-end-point',
            'oam_job_type': 'oam-job-type'
        }

        self._operational_state = operational_state
        self._lifecycle_state = lifecycle_state
        self._administrative_state = administrative_state
        self._name = name
        self._uuid = uuid
        self._schedule = schedule
        self._oam_profile = oam_profile
        self._pm_current_data = pm_current_data
        self._creation_time = creation_time
        self._oam_service_end_point = oam_service_end_point
        self._oam_job_type = oam_job_type

    @classmethod
    def from_dict(cls, dikt) -> 'TapiOamOamJob':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.oam.OamJob of this TapiOamOamJob.  # noqa: E501
        :rtype: TapiOamOamJob
        """
        return util.deserialize_model(dikt, cls)

    @property
    def operational_state(self):
        """Gets the operational_state of this TapiOamOamJob.


        :return: The operational_state of this TapiOamOamJob.
        :rtype: TapiCommonOperationalState
        """
        return self._operational_state

    @operational_state.setter
    def operational_state(self, operational_state):
        """Sets the operational_state of this TapiOamOamJob.


        :param operational_state: The operational_state of this TapiOamOamJob.
        :type operational_state: TapiCommonOperationalState
        """

        self._operational_state = operational_state

    @property
    def lifecycle_state(self):
        """Gets the lifecycle_state of this TapiOamOamJob.


        :return: The lifecycle_state of this TapiOamOamJob.
        :rtype: TapiCommonLifecycleState
        """
        return self._lifecycle_state

    @lifecycle_state.setter
    def lifecycle_state(self, lifecycle_state):
        """Sets the lifecycle_state of this TapiOamOamJob.


        :param lifecycle_state: The lifecycle_state of this TapiOamOamJob.
        :type lifecycle_state: TapiCommonLifecycleState
        """

        self._lifecycle_state = lifecycle_state

    @property
    def administrative_state(self):
        """Gets the administrative_state of this TapiOamOamJob.


        :return: The administrative_state of this TapiOamOamJob.
        :rtype: TapiCommonAdministrativeState
        """
        return self._administrative_state

    @administrative_state.setter
    def administrative_state(self, administrative_state):
        """Sets the administrative_state of this TapiOamOamJob.


        :param administrative_state: The administrative_state of this TapiOamOamJob.
        :type administrative_state: TapiCommonAdministrativeState
        """

        self._administrative_state = administrative_state

    @property
    def name(self):
        """Gets the name of this TapiOamOamJob.

        List of names. A property of an entity with a value that is unique in some namespace but may change during the life of the entity. A name carries no semantics with respect to the purpose of the entity.  # noqa: E501

        :return: The name of this TapiOamOamJob.
        :rtype: List[TapiCommonNameAndValue]
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TapiOamOamJob.

        List of names. A property of an entity with a value that is unique in some namespace but may change during the life of the entity. A name carries no semantics with respect to the purpose of the entity.  # noqa: E501

        :param name: The name of this TapiOamOamJob.
        :type name: List[TapiCommonNameAndValue]
        """

        self._name = name

    @property
    def uuid(self):
        """Gets the uuid of this TapiOamOamJob.

        UUID: An identifier that is universally unique within an identifier space, where the identifier space is itself globally unique, and immutable. An UUID carries no semantics with respect to the purpose or state of the entity.                      UUID here uses string representation as defined in RFC 4122.  The canonical representation uses lowercase characters.                      Pattern: [0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-' + '[0-9a-fA-F]{4}-[0-9a-fA-F]{12}                       Example of a UUID in string representation: f81d4fae-7dec-11d0-a765-00a0c91e6bf6  # noqa: E501

        :return: The uuid of this TapiOamOamJob.
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this TapiOamOamJob.

        UUID: An identifier that is universally unique within an identifier space, where the identifier space is itself globally unique, and immutable. An UUID carries no semantics with respect to the purpose or state of the entity.                      UUID here uses string representation as defined in RFC 4122.  The canonical representation uses lowercase characters.                      Pattern: [0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-' + '[0-9a-fA-F]{4}-[0-9a-fA-F]{12}                       Example of a UUID in string representation: f81d4fae-7dec-11d0-a765-00a0c91e6bf6  # noqa: E501

        :param uuid: The uuid of this TapiOamOamJob.
        :type uuid: str
        """

        self._uuid = uuid

    @property
    def schedule(self):
        """Gets the schedule of this TapiOamOamJob.


        :return: The schedule of this TapiOamOamJob.
        :rtype: TapiCommonTimeRange
        """
        return self._schedule

    @schedule.setter
    def schedule(self, schedule):
        """Sets the schedule of this TapiOamOamJob.


        :param schedule: The schedule of this TapiOamOamJob.
        :type schedule: TapiCommonTimeRange
        """

        self._schedule = schedule

    @property
    def oam_profile(self):
        """Gets the oam_profile of this TapiOamOamJob.


        :return: The oam_profile of this TapiOamOamJob.
        :rtype: TapiOamOamProfileRef
        """
        return self._oam_profile

    @oam_profile.setter
    def oam_profile(self, oam_profile):
        """Sets the oam_profile of this TapiOamOamJob.


        :param oam_profile: The oam_profile of this TapiOamOamJob.
        :type oam_profile: TapiOamOamProfileRef
        """

        self._oam_profile = oam_profile

    @property
    def pm_current_data(self):
        """Gets the pm_current_data of this TapiOamOamJob.

        Granularity period of the CurrentData identifies the specific CurrentData instance in the scope of this OamJob.                      For example, typically at least                      one 15min and                      one 24hr;                      optionally one additional configurable (< 15min)  # noqa: E501

        :return: The pm_current_data of this TapiOamOamJob.
        :rtype: List[TapiOamPmCurrentData]
        """
        return self._pm_current_data

    @pm_current_data.setter
    def pm_current_data(self, pm_current_data):
        """Sets the pm_current_data of this TapiOamOamJob.

        Granularity period of the CurrentData identifies the specific CurrentData instance in the scope of this OamJob.                      For example, typically at least                      one 15min and                      one 24hr;                      optionally one additional configurable (< 15min)  # noqa: E501

        :param pm_current_data: The pm_current_data of this TapiOamOamJob.
        :type pm_current_data: List[TapiOamPmCurrentData]
        """

        self._pm_current_data = pm_current_data

    @property
    def creation_time(self):
        """Gets the creation_time of this TapiOamOamJob.

        none  # noqa: E501

        :return: The creation_time of this TapiOamOamJob.
        :rtype: str
        """
        return self._creation_time

    @creation_time.setter
    def creation_time(self, creation_time):
        """Sets the creation_time of this TapiOamOamJob.

        none  # noqa: E501

        :param creation_time: The creation_time of this TapiOamOamJob.
        :type creation_time: str
        """

        self._creation_time = creation_time

    @property
    def oam_service_end_point(self):
        """Gets the oam_service_end_point of this TapiOamOamJob.

        none  # noqa: E501

        :return: The oam_service_end_point of this TapiOamOamJob.
        :rtype: List[TapiOamOamServiceEndPointRef]
        """
        return self._oam_service_end_point

    @oam_service_end_point.setter
    def oam_service_end_point(self, oam_service_end_point):
        """Sets the oam_service_end_point of this TapiOamOamJob.

        none  # noqa: E501

        :param oam_service_end_point: The oam_service_end_point of this TapiOamOamJob.
        :type oam_service_end_point: List[TapiOamOamServiceEndPointRef]
        """

        self._oam_service_end_point = oam_service_end_point

    @property
    def oam_job_type(self):
        """Gets the oam_job_type of this TapiOamOamJob.

        none  # noqa: E501

        :return: The oam_job_type of this TapiOamOamJob.
        :rtype: str
        """
        return self._oam_job_type

    @oam_job_type.setter
    def oam_job_type(self, oam_job_type):
        """Sets the oam_job_type of this TapiOamOamJob.

        none  # noqa: E501

        :param oam_job_type: The oam_job_type of this TapiOamOamJob.
        :type oam_job_type: str
        """

        self._oam_job_type = oam_job_type
