# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_common_time_unit import TapiCommonTimeUnit  # noqa: F401,E501
from tapi_server import util


class TapiCommonTimePeriod(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, value=None, unit=None):  # noqa: E501
        """TapiCommonTimePeriod - a model defined in OpenAPI

        :param value: The value of this TapiCommonTimePeriod.  # noqa: E501
        :type value: int
        :param unit: The unit of this TapiCommonTimePeriod.  # noqa: E501
        :type unit: TapiCommonTimeUnit
        """
        self.openapi_types = {
            'value': int,
            'unit': TapiCommonTimeUnit
        }

        self.attribute_map = {
            'value': 'value',
            'unit': 'unit'
        }

        self._value = value
        self._unit = unit

    @classmethod
    def from_dict(cls, dikt) -> 'TapiCommonTimePeriod':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.common.TimePeriod of this TapiCommonTimePeriod.  # noqa: E501
        :rtype: TapiCommonTimePeriod
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self):
        """Gets the value of this TapiCommonTimePeriod.

        none  # noqa: E501

        :return: The value of this TapiCommonTimePeriod.
        :rtype: int
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this TapiCommonTimePeriod.

        none  # noqa: E501

        :param value: The value of this TapiCommonTimePeriod.
        :type value: int
        """

        self._value = value

    @property
    def unit(self):
        """Gets the unit of this TapiCommonTimePeriod.


        :return: The unit of this TapiCommonTimePeriod.
        :rtype: TapiCommonTimeUnit
        """
        return self._unit

    @unit.setter
    def unit(self, unit):
        """Sets the unit of this TapiCommonTimePeriod.


        :param unit: The unit of this TapiCommonTimePeriod.
        :type unit: TapiCommonTimeUnit
        """

        self._unit = unit
