# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server import util


class TapiConnectivityDeleteconnectivityserviceInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, service_id_or_name=None):  # noqa: E501
        """TapiConnectivityDeleteconnectivityserviceInput - a model defined in OpenAPI

        :param service_id_or_name: The service_id_or_name of this TapiConnectivityDeleteconnectivityserviceInput.  # noqa: E501
        :type service_id_or_name: str
        """
        self.openapi_types = {
            'service_id_or_name': str
        }

        self.attribute_map = {
            'service_id_or_name': 'service-id-or-name'
        }

        self._service_id_or_name = service_id_or_name

    @classmethod
    def from_dict(cls, dikt) -> 'TapiConnectivityDeleteconnectivityserviceInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.connectivity.deleteconnectivityservice.Input of this TapiConnectivityDeleteconnectivityserviceInput.  # noqa: E501
        :rtype: TapiConnectivityDeleteconnectivityserviceInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def service_id_or_name(self):
        """Gets the service_id_or_name of this TapiConnectivityDeleteconnectivityserviceInput.

        none  # noqa: E501

        :return: The service_id_or_name of this TapiConnectivityDeleteconnectivityserviceInput.
        :rtype: str
        """
        return self._service_id_or_name

    @service_id_or_name.setter
    def service_id_or_name(self, service_id_or_name):
        """Sets the service_id_or_name of this TapiConnectivityDeleteconnectivityserviceInput.

        none  # noqa: E501

        :param service_id_or_name: The service_id_or_name of this TapiConnectivityDeleteconnectivityserviceInput.
        :type service_id_or_name: str
        """

        self._service_id_or_name = service_id_or_name
