# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_topology_getnodeedgepointdetails_output_node_edge_point import TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint  # noqa: F401,E501
from tapi_server import util


class TapiTopologyGetnodeedgepointdetailsOutput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, node_edge_point=None):  # noqa: E501
        """TapiTopologyGetnodeedgepointdetailsOutput - a model defined in OpenAPI

        :param node_edge_point: The node_edge_point of this TapiTopologyGetnodeedgepointdetailsOutput.  # noqa: E501
        :type node_edge_point: TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint
        """
        self.openapi_types = {
            'node_edge_point': TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint
        }

        self.attribute_map = {
            'node_edge_point': 'node-edge-point'
        }

        self._node_edge_point = node_edge_point

    @classmethod
    def from_dict(cls, dikt) -> 'TapiTopologyGetnodeedgepointdetailsOutput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.topology.getnodeedgepointdetails.Output of this TapiTopologyGetnodeedgepointdetailsOutput.  # noqa: E501
        :rtype: TapiTopologyGetnodeedgepointdetailsOutput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def node_edge_point(self):
        """Gets the node_edge_point of this TapiTopologyGetnodeedgepointdetailsOutput.


        :return: The node_edge_point of this TapiTopologyGetnodeedgepointdetailsOutput.
        :rtype: TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint
        """
        return self._node_edge_point

    @node_edge_point.setter
    def node_edge_point(self, node_edge_point):
        """Sets the node_edge_point of this TapiTopologyGetnodeedgepointdetailsOutput.


        :param node_edge_point: The node_edge_point of this TapiTopologyGetnodeedgepointdetailsOutput.
        :type node_edge_point: TapiTopologyGetnodeedgepointdetailsOutputNodeEdgePoint
        """

        self._node_edge_point = node_edge_point
