# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_topology_gettopologylist_output import TapiTopologyGettopologylistOutput  # noqa: F401,E501
from tapi_server import util


class TapiTopologyGetTopologyList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, output=None):  # noqa: E501
        """TapiTopologyGetTopologyList - a model defined in OpenAPI

        :param output: The output of this TapiTopologyGetTopologyList.  # noqa: E501
        :type output: TapiTopologyGettopologylistOutput
        """
        self.openapi_types = {
            'output': TapiTopologyGettopologylistOutput
        }

        self.attribute_map = {
            'output': 'output'
        }

        self._output = output

    @classmethod
    def from_dict(cls, dikt) -> 'TapiTopologyGetTopologyList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.topology.GetTopologyList of this TapiTopologyGetTopologyList.  # noqa: E501
        :rtype: TapiTopologyGetTopologyList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def output(self):
        """Gets the output of this TapiTopologyGetTopologyList.


        :return: The output of this TapiTopologyGetTopologyList.
        :rtype: TapiTopologyGettopologylistOutput
        """
        return self._output

    @output.setter
    def output(self, output):
        """Sets the output of this TapiTopologyGetTopologyList.


        :param output: The output of this TapiTopologyGetTopologyList.
        :type output: TapiTopologyGettopologylistOutput
        """

        self._output = output
