# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_oam_mep_ref import TapiOamMepRef  # noqa: F401,E501
from tapi_server.models.tapi_oam_mip_ref import TapiOamMipRef  # noqa: F401,E501
from tapi_server import util


class TapiOamMepMipList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, mip=None, mep=None):  # noqa: E501
        """TapiOamMepMipList - a model defined in OpenAPI

        :param mip: The mip of this TapiOamMepMipList.  # noqa: E501
        :type mip: List[TapiOamMipRef]
        :param mep: The mep of this TapiOamMepMipList.  # noqa: E501
        :type mep: List[TapiOamMepRef]
        """
        self.openapi_types = {
            'mip': List[TapiOamMipRef],
            'mep': List[TapiOamMepRef]
        }

        self.attribute_map = {
            'mip': 'mip',
            'mep': 'mep'
        }

        self._mip = mip
        self._mep = mep

    @classmethod
    def from_dict(cls, dikt) -> 'TapiOamMepMipList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.oam.MepMipList of this TapiOamMepMipList.  # noqa: E501
        :rtype: TapiOamMepMipList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def mip(self):
        """Gets the mip of this TapiOamMepMipList.

        none  # noqa: E501

        :return: The mip of this TapiOamMepMipList.
        :rtype: List[TapiOamMipRef]
        """
        return self._mip

    @mip.setter
    def mip(self, mip):
        """Sets the mip of this TapiOamMepMipList.

        none  # noqa: E501

        :param mip: The mip of this TapiOamMepMipList.
        :type mip: List[TapiOamMipRef]
        """

        self._mip = mip

    @property
    def mep(self):
        """Gets the mep of this TapiOamMepMipList.

        none  # noqa: E501

        :return: The mep of this TapiOamMepMipList.
        :rtype: List[TapiOamMepRef]
        """
        return self._mep

    @mep.setter
    def mep(self, mep):
        """Sets the mep of this TapiOamMepMipList.

        none  # noqa: E501

        :param mep: The mep of this TapiOamMepMipList.
        :type mep: List[TapiOamMepRef]
        """

        self._mep = mep
