# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_oam_updateoamjob_output import TapiOamUpdateoamjobOutput  # noqa: F401,E501
from tapi_server import util


class TapiOamUpdateOamJob(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, output=None):  # noqa: E501
        """TapiOamUpdateOamJob - a model defined in OpenAPI

        :param output: The output of this TapiOamUpdateOamJob.  # noqa: E501
        :type output: TapiOamUpdateoamjobOutput
        """
        self.openapi_types = {
            'output': TapiOamUpdateoamjobOutput
        }

        self.attribute_map = {
            'output': 'output'
        }

        self._output = output

    @classmethod
    def from_dict(cls, dikt) -> 'TapiOamUpdateOamJob':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.oam.UpdateOamJob of this TapiOamUpdateOamJob.  # noqa: E501
        :rtype: TapiOamUpdateOamJob
        """
        return util.deserialize_model(dikt, cls)

    @property
    def output(self):
        """Gets the output of this TapiOamUpdateOamJob.


        :return: The output of this TapiOamUpdateOamJob.
        :rtype: TapiOamUpdateoamjobOutput
        """
        return self._output

    @output.setter
    def output(self, output):
        """Sets the output of this TapiOamUpdateOamJob.


        :param output: The output of this TapiOamUpdateOamJob.
        :type output: TapiOamUpdateoamjobOutput
        """

        self._output = output
