# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_oam_oam_constraint import TapiOamOamConstraint  # noqa: F401,E501
from tapi_server.models.tapi_oam_oam_service_end_point import TapiOamOamServiceEndPoint  # noqa: F401,E501
from tapi_server import util


class TapiOamUpdateoamserviceInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, oam_constraint=None, service_id=None, state=None, end_point=None):  # noqa: E501
        """TapiOamUpdateoamserviceInput - a model defined in OpenAPI

        :param oam_constraint: The oam_constraint of this TapiOamUpdateoamserviceInput.  # noqa: E501
        :type oam_constraint: TapiOamOamConstraint
        :param service_id: The service_id of this TapiOamUpdateoamserviceInput.  # noqa: E501
        :type service_id: str
        :param state: The state of this TapiOamUpdateoamserviceInput.  # noqa: E501
        :type state: str
        :param end_point: The end_point of this TapiOamUpdateoamserviceInput.  # noqa: E501
        :type end_point: List[TapiOamOamServiceEndPoint]
        """
        self.openapi_types = {
            'oam_constraint': TapiOamOamConstraint,
            'service_id': str,
            'state': str,
            'end_point': List[TapiOamOamServiceEndPoint]
        }

        self.attribute_map = {
            'oam_constraint': 'oam-constraint',
            'service_id': 'service-id',
            'state': 'state',
            'end_point': 'end-point'
        }

        self._oam_constraint = oam_constraint
        self._service_id = service_id
        self._state = state
        self._end_point = end_point

    @classmethod
    def from_dict(cls, dikt) -> 'TapiOamUpdateoamserviceInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.oam.updateoamservice.Input of this TapiOamUpdateoamserviceInput.  # noqa: E501
        :rtype: TapiOamUpdateoamserviceInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def oam_constraint(self):
        """Gets the oam_constraint of this TapiOamUpdateoamserviceInput.


        :return: The oam_constraint of this TapiOamUpdateoamserviceInput.
        :rtype: TapiOamOamConstraint
        """
        return self._oam_constraint

    @oam_constraint.setter
    def oam_constraint(self, oam_constraint):
        """Sets the oam_constraint of this TapiOamUpdateoamserviceInput.


        :param oam_constraint: The oam_constraint of this TapiOamUpdateoamserviceInput.
        :type oam_constraint: TapiOamOamConstraint
        """

        self._oam_constraint = oam_constraint

    @property
    def service_id(self):
        """Gets the service_id of this TapiOamUpdateoamserviceInput.

        none  # noqa: E501

        :return: The service_id of this TapiOamUpdateoamserviceInput.
        :rtype: str
        """
        return self._service_id

    @service_id.setter
    def service_id(self, service_id):
        """Sets the service_id of this TapiOamUpdateoamserviceInput.

        none  # noqa: E501

        :param service_id: The service_id of this TapiOamUpdateoamserviceInput.
        :type service_id: str
        """

        self._service_id = service_id

    @property
    def state(self):
        """Gets the state of this TapiOamUpdateoamserviceInput.

        none  # noqa: E501

        :return: The state of this TapiOamUpdateoamserviceInput.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this TapiOamUpdateoamserviceInput.

        none  # noqa: E501

        :param state: The state of this TapiOamUpdateoamserviceInput.
        :type state: str
        """

        self._state = state

    @property
    def end_point(self):
        """Gets the end_point of this TapiOamUpdateoamserviceInput.

        none  # noqa: E501

        :return: The end_point of this TapiOamUpdateoamserviceInput.
        :rtype: List[TapiOamOamServiceEndPoint]
        """
        return self._end_point

    @end_point.setter
    def end_point(self, end_point):
        """Sets the end_point of this TapiOamUpdateoamserviceInput.

        none  # noqa: E501

        :param end_point: The end_point of this TapiOamUpdateoamserviceInput.
        :type end_point: List[TapiOamOamServiceEndPoint]
        """

        self._end_point = end_point
