# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_notification_notification_context import TapiNotificationNotificationContext  # noqa: F401,E501
from tapi_server import util


class TapiNotificationContextAugmentation2(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, notification_context=None):  # noqa: E501
        """TapiNotificationContextAugmentation2 - a model defined in OpenAPI

        :param notification_context: The notification_context of this TapiNotificationContextAugmentation2.  # noqa: E501
        :type notification_context: TapiNotificationNotificationContext
        """
        self.openapi_types = {
            'notification_context': TapiNotificationNotificationContext
        }

        self.attribute_map = {
            'notification_context': 'notification-context'
        }

        self._notification_context = notification_context

    @classmethod
    def from_dict(cls, dikt) -> 'TapiNotificationContextAugmentation2':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.notification.ContextAugmentation2 of this TapiNotificationContextAugmentation2.  # noqa: E501
        :rtype: TapiNotificationContextAugmentation2
        """
        return util.deserialize_model(dikt, cls)

    @property
    def notification_context(self):
        """Gets the notification_context of this TapiNotificationContextAugmentation2.


        :return: The notification_context of this TapiNotificationContextAugmentation2.
        :rtype: TapiNotificationNotificationContext
        """
        return self._notification_context

    @notification_context.setter
    def notification_context(self, notification_context):
        """Sets the notification_context of this TapiNotificationContextAugmentation2.


        :param notification_context: The notification_context of this TapiNotificationContextAugmentation2.
        :type notification_context: TapiNotificationNotificationContext
        """

        self._notification_context = notification_context
