# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server import util


class TapiCommonBandwidthProfileType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    MEF_10_X = "MEF_10.x"
    RFC_2697 = "RFC_2697"
    RFC_2698 = "RFC_2698"
    RFC_4115 = "RFC_4115"

    def __init__(self):  # noqa: E501
        """TapiCommonBandwidthProfileType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'TapiCommonBandwidthProfileType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.common.BandwidthProfileType of this TapiCommonBandwidthProfileType.  # noqa: E501
        :rtype: TapiCommonBandwidthProfileType
        """
        return util.deserialize_model(dikt, cls)
