# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_topology_getnodeedgepointdetails_output import TapiTopologyGetnodeedgepointdetailsOutput  # noqa: F401,E501
from tapi_server import util


class TapiTopologyGetNodeEdgePointDetails(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, output=None):  # noqa: E501
        """TapiTopologyGetNodeEdgePointDetails - a model defined in OpenAPI

        :param output: The output of this TapiTopologyGetNodeEdgePointDetails.  # noqa: E501
        :type output: TapiTopologyGetnodeedgepointdetailsOutput
        """
        self.openapi_types = {
            'output': TapiTopologyGetnodeedgepointdetailsOutput
        }

        self.attribute_map = {
            'output': 'output'
        }

        self._output = output

    @classmethod
    def from_dict(cls, dikt) -> 'TapiTopologyGetNodeEdgePointDetails':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.topology.GetNodeEdgePointDetails of this TapiTopologyGetNodeEdgePointDetails.  # noqa: E501
        :rtype: TapiTopologyGetNodeEdgePointDetails
        """
        return util.deserialize_model(dikt, cls)

    @property
    def output(self):
        """Gets the output of this TapiTopologyGetNodeEdgePointDetails.


        :return: The output of this TapiTopologyGetNodeEdgePointDetails.
        :rtype: TapiTopologyGetnodeedgepointdetailsOutput
        """
        return self._output

    @output.setter
    def output(self, output):
        """Sets the output of this TapiTopologyGetNodeEdgePointDetails.


        :param output: The output of this TapiTopologyGetNodeEdgePointDetails.
        :type output: TapiTopologyGetnodeedgepointdetailsOutput
        """

        self._output = output
