# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_oam_oam_profile import TapiOamOamProfile  # noqa: F401,E501
from tapi_server import util


class TapiOamUpdateoamjobInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, job_id=None, schedule=None, oam_profile=None, state=None):  # noqa: E501
        """TapiOamUpdateoamjobInput - a model defined in OpenAPI

        :param job_id: The job_id of this TapiOamUpdateoamjobInput.  # noqa: E501
        :type job_id: str
        :param schedule: The schedule of this TapiOamUpdateoamjobInput.  # noqa: E501
        :type schedule: str
        :param oam_profile: The oam_profile of this TapiOamUpdateoamjobInput.  # noqa: E501
        :type oam_profile: TapiOamOamProfile
        :param state: The state of this TapiOamUpdateoamjobInput.  # noqa: E501
        :type state: str
        """
        self.openapi_types = {
            'job_id': str,
            'schedule': str,
            'oam_profile': TapiOamOamProfile,
            'state': str
        }

        self.attribute_map = {
            'job_id': 'job-id',
            'schedule': 'schedule',
            'oam_profile': 'oam-profile',
            'state': 'state'
        }

        self._job_id = job_id
        self._schedule = schedule
        self._oam_profile = oam_profile
        self._state = state

    @classmethod
    def from_dict(cls, dikt) -> 'TapiOamUpdateoamjobInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.oam.updateoamjob.Input of this TapiOamUpdateoamjobInput.  # noqa: E501
        :rtype: TapiOamUpdateoamjobInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def job_id(self):
        """Gets the job_id of this TapiOamUpdateoamjobInput.

        none  # noqa: E501

        :return: The job_id of this TapiOamUpdateoamjobInput.
        :rtype: str
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id):
        """Sets the job_id of this TapiOamUpdateoamjobInput.

        none  # noqa: E501

        :param job_id: The job_id of this TapiOamUpdateoamjobInput.
        :type job_id: str
        """

        self._job_id = job_id

    @property
    def schedule(self):
        """Gets the schedule of this TapiOamUpdateoamjobInput.

        none  # noqa: E501

        :return: The schedule of this TapiOamUpdateoamjobInput.
        :rtype: str
        """
        return self._schedule

    @schedule.setter
    def schedule(self, schedule):
        """Sets the schedule of this TapiOamUpdateoamjobInput.

        none  # noqa: E501

        :param schedule: The schedule of this TapiOamUpdateoamjobInput.
        :type schedule: str
        """

        self._schedule = schedule

    @property
    def oam_profile(self):
        """Gets the oam_profile of this TapiOamUpdateoamjobInput.


        :return: The oam_profile of this TapiOamUpdateoamjobInput.
        :rtype: TapiOamOamProfile
        """
        return self._oam_profile

    @oam_profile.setter
    def oam_profile(self, oam_profile):
        """Sets the oam_profile of this TapiOamUpdateoamjobInput.


        :param oam_profile: The oam_profile of this TapiOamUpdateoamjobInput.
        :type oam_profile: TapiOamOamProfile
        """

        self._oam_profile = oam_profile

    @property
    def state(self):
        """Gets the state of this TapiOamUpdateoamjobInput.

        none  # noqa: E501

        :return: The state of this TapiOamUpdateoamjobInput.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this TapiOamUpdateoamjobInput.

        none  # noqa: E501

        :param state: The state of this TapiOamUpdateoamjobInput.
        :type state: str
        """

        self._state = state
