# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_topology_node_edge_point_ref import TapiTopologyNodeEdgePointRef  # noqa: F401,E501
from tapi_server import util


class TapiConnectivityConnectionEndPointRef(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, topology_uuid=None, node_uuid=None, node_edge_point_uuid=None, connection_end_point_uuid=None):  # noqa: E501
        """TapiConnectivityConnectionEndPointRef - a model defined in OpenAPI

        :param topology_uuid: The topology_uuid of this TapiConnectivityConnectionEndPointRef.  # noqa: E501
        :type topology_uuid: str
        :param node_uuid: The node_uuid of this TapiConnectivityConnectionEndPointRef.  # noqa: E501
        :type node_uuid: str
        :param node_edge_point_uuid: The node_edge_point_uuid of this TapiConnectivityConnectionEndPointRef.  # noqa: E501
        :type node_edge_point_uuid: str
        :param connection_end_point_uuid: The connection_end_point_uuid of this TapiConnectivityConnectionEndPointRef.  # noqa: E501
        :type connection_end_point_uuid: str
        """
        self.openapi_types = {
            'topology_uuid': str,
            'node_uuid': str,
            'node_edge_point_uuid': str,
            'connection_end_point_uuid': str
        }

        self.attribute_map = {
            'topology_uuid': 'topology-uuid',
            'node_uuid': 'node-uuid',
            'node_edge_point_uuid': 'node-edge-point-uuid',
            'connection_end_point_uuid': 'connection-end-point-uuid'
        }

        self._topology_uuid = topology_uuid
        self._node_uuid = node_uuid
        self._node_edge_point_uuid = node_edge_point_uuid
        self._connection_end_point_uuid = connection_end_point_uuid

    @classmethod
    def from_dict(cls, dikt) -> 'TapiConnectivityConnectionEndPointRef':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.connectivity.ConnectionEndPointRef of this TapiConnectivityConnectionEndPointRef.  # noqa: E501
        :rtype: TapiConnectivityConnectionEndPointRef
        """
        return util.deserialize_model(dikt, cls)

    @property
    def topology_uuid(self):
        """Gets the topology_uuid of this TapiConnectivityConnectionEndPointRef.

        none  # noqa: E501

        :return: The topology_uuid of this TapiConnectivityConnectionEndPointRef.
        :rtype: str
        """
        return self._topology_uuid

    @topology_uuid.setter
    def topology_uuid(self, topology_uuid):
        """Sets the topology_uuid of this TapiConnectivityConnectionEndPointRef.

        none  # noqa: E501

        :param topology_uuid: The topology_uuid of this TapiConnectivityConnectionEndPointRef.
        :type topology_uuid: str
        """

        self._topology_uuid = topology_uuid

    @property
    def node_uuid(self):
        """Gets the node_uuid of this TapiConnectivityConnectionEndPointRef.

        none  # noqa: E501

        :return: The node_uuid of this TapiConnectivityConnectionEndPointRef.
        :rtype: str
        """
        return self._node_uuid

    @node_uuid.setter
    def node_uuid(self, node_uuid):
        """Sets the node_uuid of this TapiConnectivityConnectionEndPointRef.

        none  # noqa: E501

        :param node_uuid: The node_uuid of this TapiConnectivityConnectionEndPointRef.
        :type node_uuid: str
        """

        self._node_uuid = node_uuid

    @property
    def node_edge_point_uuid(self):
        """Gets the node_edge_point_uuid of this TapiConnectivityConnectionEndPointRef.

        none  # noqa: E501

        :return: The node_edge_point_uuid of this TapiConnectivityConnectionEndPointRef.
        :rtype: str
        """
        return self._node_edge_point_uuid

    @node_edge_point_uuid.setter
    def node_edge_point_uuid(self, node_edge_point_uuid):
        """Sets the node_edge_point_uuid of this TapiConnectivityConnectionEndPointRef.

        none  # noqa: E501

        :param node_edge_point_uuid: The node_edge_point_uuid of this TapiConnectivityConnectionEndPointRef.
        :type node_edge_point_uuid: str
        """

        self._node_edge_point_uuid = node_edge_point_uuid

    @property
    def connection_end_point_uuid(self):
        """Gets the connection_end_point_uuid of this TapiConnectivityConnectionEndPointRef.

        none  # noqa: E501

        :return: The connection_end_point_uuid of this TapiConnectivityConnectionEndPointRef.
        :rtype: str
        """
        return self._connection_end_point_uuid

    @connection_end_point_uuid.setter
    def connection_end_point_uuid(self, connection_end_point_uuid):
        """Sets the connection_end_point_uuid of this TapiConnectivityConnectionEndPointRef.

        none  # noqa: E501

        :param connection_end_point_uuid: The connection_end_point_uuid of this TapiConnectivityConnectionEndPointRef.
        :type connection_end_point_uuid: str
        """

        self._connection_end_point_uuid = connection_end_point_uuid
