# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_connectivity_createconnectivityservice_output_service import TapiConnectivityCreateconnectivityserviceOutputService  # noqa: F401,E501
from tapi_server import util


class TapiConnectivityCreateconnectivityserviceOutput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, service=None):  # noqa: E501
        """TapiConnectivityCreateconnectivityserviceOutput - a model defined in OpenAPI

        :param service: The service of this TapiConnectivityCreateconnectivityserviceOutput.  # noqa: E501
        :type service: TapiConnectivityCreateconnectivityserviceOutputService
        """
        self.openapi_types = {
            'service': TapiConnectivityCreateconnectivityserviceOutputService
        }

        self.attribute_map = {
            'service': 'service'
        }

        self._service = service

    @classmethod
    def from_dict(cls, dikt) -> 'TapiConnectivityCreateconnectivityserviceOutput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.connectivity.createconnectivityservice.Output of this TapiConnectivityCreateconnectivityserviceOutput.  # noqa: E501
        :rtype: TapiConnectivityCreateconnectivityserviceOutput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def service(self):
        """Gets the service of this TapiConnectivityCreateconnectivityserviceOutput.


        :return: The service of this TapiConnectivityCreateconnectivityserviceOutput.
        :rtype: TapiConnectivityCreateconnectivityserviceOutputService
        """
        return self._service

    @service.setter
    def service(self, service):
        """Sets the service of this TapiConnectivityCreateconnectivityserviceOutput.


        :param service: The service of this TapiConnectivityCreateconnectivityserviceOutput.
        :type service: TapiConnectivityCreateconnectivityserviceOutputService
        """

        self._service = service
